openapi: 3.0.3
info:
  title: JWT REST API
  description: A REST API using Go and JWT for authentication.
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Todo:
      type: object
      properties:
        title:
          type: string
          example: "Buy milk"
    User:
      type: object
      properties:
        username:
          type: string
          example: "admin"
        password:
          type: string
          example: "password"
    Tokens:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
security:
  - bearerAuth: []
paths:
  /login:
    post:
      summary: Login
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
  /logout:
    post:
      summary: Logout
      responses:
        '200':
          description: Successful logout
  /token/refresh:
    post:
      summary: Refresh Token
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
      responses:
        '201':
          description: New tokens generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
  /todo:
    post:
      summary: Create a new Todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '201':
          description: Created
